apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: mypubsub
spec:
  type: pubsub.kafka
  version: v1
  metadata:
    - name: brokers
      value: "kafka:29092"
    - name: consumerGroup
      value: "{namespace}"
    - name: authType
      value: "none"
    - name: authRequired
      value: "false"
    - name: clientID
      value: "publisher-client"
    - name: disableTls # Optional. Disable TLS. This is not safe for production!! You should read the `Mutual TLS` section for how to use TLS.
      value: "true"