apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: mypubsub
spec:
  type: pubsub.kafka
  version: v1
  metadata:
    - name: brokers
      value: "172.28.1.2:9092"
    - name: authType
      value: "none"
